mtmse/dotify.library

integrationtest/org/daisy/dotify/formatter/test/LayoutEngineTest.java

Hi @PaulRambags and @bertfrees
I found a test that failed without reason for me while working, and after a lot of headaches, I realized it had to do with line endings. These tests are not required for the framework and make the testing brittle and hard to work with.
This PR will change the test from doing a byte compare to a line compare where it checks if the files' strings are equal, which is less strict and more secure when running on multiple platforms.
Best regards
Daniel

Make test less brittle.

---

src/org/daisy/dotify/translator/impl/liblouis/LiblouisBrailleFilter.java

Hi @bertfrees and @PaulRambags 
This is a really small bug fix.
We found that during the production of children's literature where the braille output should not have markers for capital letters the function threw Runtime exception that the hyphenated text and the input text were not equal on line 316 in this same file.
In order to solve this, we moved the assignment of the hyphenation string to after we had updated the casing of the string.
This solved the issue and seems like a reasonable fix.
Best regards
Daniel

Change so we handle the text casing the same for both original and hyphenated text.

---

src/org/daisy/dotify/translator/impl/liblouis/LiblouisBrailleFilter.java
test/org/daisy/dotify/translator/impl/liblouis/LiblouisBrailleFilterTest.java

Hi @bertfrees 
We found another interesting issue today. I created a simple test case to illustrate this issue.
When we translated a page break in a list item to OBFL and then ran the library, the problem came.
```
<li data-textflow-id="17">
<a class="pagebreak" data-page-nr="2" name="iii"/>
</li>
```
This generated the following OBFL sequence:
```
<sequence master="main" initial-page-number="1">
<block break-before="page" padding-top="3" keep-with-previous-sheets="1" id="d7e4127">
<block first-line-indent="2">Titles in the series include the following:</block>
<block padding-top="1" list-type="ol" margin-left="2">
<block first-line-indent="3" text-indent="3" block-indent="3">
<marker class="pagenum" value="iii"/>
<marker class="pagenum-turn" value="ii–"/>
</block>
</block>
</block> …
```

Crash exception when running empty blocks.

---

src/org/daisy/dotify/hyphenator/impl/JHyphenator.java
test/org/daisy/dotify/hyphenator/impl/JHypenatorTest.java

Hi @bertfrees and @PaulRambags 
We found an instance where the pre-hyphenated string was longer than the processed string. It was an issue with spacing, for some reason ```split(" ")``` trims the string or something. 
Best regards
Daniel

Fix to handle space issue.

---

src/org/daisy/dotify/formatter/impl/row/AggregatedBrailleTranslatorResult.java

@kalaspuffar @PaulRambags There was a nasty bug in AggregatedBrailleTranslatorResult that for some reason hasn't been noticed yet until now.

Fix potential endless loop in AggregatedBrailleTranslatorResult

---

src/org/daisy/dotify/formatter/impl/segment/NewLineSegment.java

@PaulRambags @kalaspuffar This is a change in the same spirit of d04c5b299c7a74fe4a327efb45cb4ee45c61eea0. Currently a NewlineSegment appears to the translator as an empty string which can result in unwanted side effects.
Related to https://github.com/daisy/pipeline/issues/603.

Let NewLineSegment.peek/resolve return a newline character

---

src/org/daisy/dotify/formatter/impl/core/Table.java

@kalaspuffar @PaulRambags We discussed in last meeting that ideally there should be a fallback solution for tables that have too many columns to fit on the page. An idea that comes to mind right now is that Dotify could simply cut off the part that overflows the page, and insert a special attribute in the PEF to indicate the location of the faulty table (similar to how "external references" are indicated).
Anyway, the most problematic part of how such tables are currently handled is the very vague error message which leaves the user clueless. This patch improves that error message.

Improve "Failed to solve table" error message

---

src/org/daisy/dotify/formatter/impl/row/RowImpl.java
src/org/daisy/dotify/formatter/impl/row/RowInfo.java
src/org/daisy/dotify/formatter/impl/row/SegmentProcessor.java

@kalaspuffar @PaulRambags Another endless loop, this time in SegmentProcessor. This is less of a bug than https://github.com/mtmse/dotify.library/pull/14 because in normal circumstances the endless loop would never happen. It's only when one tries to position a leader in such a way that it becomes impossible for Dotify to lay it out correctly that Dotify could end up in an endless loop. This is still a dangerous situation so it's better to add some checks and abort if needed.
I've also improved the code documentation.

Protect against endless loop in SegmentProcessor

---

src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
test/org/daisy/dotify/formatter/impl/FormatterImplTest.java

`display-when` was not handled correctly when a block was more than one row or when two consecutive blocks had a `display-when`.
@kalaspuffar @PaulRambags Please check out my fix for this bug.

Fix bug in `display-when` implementation

---

src/org/daisy/dotify/formatter/impl/row/AggregatedBrailleTranslatorResult.java

@kalaspuffar @PaulRambags This is a bug spotted in the code. It may not have affected anyone yet because `AggregatedBrailleTranslatorResult` is currently only used to combine segments after a leader, and it is not a common use case that there are line breaks after a leader.

Fix bug in AggregatedBrailleTranslatorResult

---

build.gradle

This fixes liblouis/liblouis-java#20
The embedded Liblouis is now version 3.19, which is compiled for UCS-4.

Update liblouis-java to latest version

---

src/org/daisy/braille/utils/impl/provider/BrailleEditorsFileFormat.java
src/org/daisy/dotify/api/embosser/FileFormatProperties.java

@kalaspuffar @PaulRambags I added this new method to allow file format implementations to indicate whether a single file can contain multiple volumes or not. This is because currently when DAISY Pipeline stores the result of a braille conversion in a braille file (BRF), it always creates a separate file for each volume, but I'd like to support formats (notably PEF itself) that can contain multiple volumes.

Add new "supportsVolume" method to FileFormat API

---

src/org/daisy/dotify/api/formatter/BlockContentBuilder.java
src/org/daisy/dotify/formatter/impl/core/FormatterCoreImpl.java
src/org/daisy/dotify/formatter/impl/core/TableOfContentsImpl.java
src/org/daisy/dotify/formatter/impl/obfl/ObflParserImpl.java
src/org/daisy/dotify/formatter/impl/row/LeaderManager.java
src/org/daisy/dotify/formatter/impl/row/SegmentProcessor.java
src/org/daisy/dotify/formatter/impl/segment/LeaderSegment.java
src/org/daisy/dotify/formatter/impl/volume/VolumeContentBuilderImpl.java
test/org/daisy/dotify/formatter/impl/row/BlockContentManagerTest.java

@kalaspuffar @PaulRambags I've made it a bit more logical how a leader pattern is translated.
Dotify now uses the mode that applies on `leader` element, that is, the mode that is computed by starting from the `leader` element and taking the `translate` attribute of the first ancestor that has the attribute, or else the specified value for the "mode" option. Before, Dotify took the mode of the first text segment after or before the leader element. This was less logical and made it impossible to specify different modes on the leader pattern and the surrounding text.

To translate leader pattern use mode that applies on leader element

---

src/org/daisy/dotify/formatter/impl/obfl/ObflParserImpl.java
src/org/daisy/dotify/formatter/impl/page/PageSequenceBuilder2.java
src/org/daisy/dotify/formatter/impl/page/RowGroup.java
src/org/daisy/dotify/formatter/impl/page/RowGroupDataSource.java
src/org/daisy/dotify/formatter/impl/page/RowGroupProvider.java
test/org/daisy/dotify/formatter/impl/FormatterImplTest.java

@kalaspuffar @PaulRambags I've improved the implementation of the "display-when" attirbute:
- The issue of unused available space at the bottom of the page is fixed (see https://github.com/mtmse/dotify.library/issues/22).
- It is not required anymore to add a `keep="page"` on elements with `display-when`.
- In theory we could now support other conditions than `(! $starts-at-top-of-page)`.

Improve implementation of "display-when" attribute

---

src/org/daisy/dotify/formatter/impl/VolumeProvider.java

@kalaspuffar I think this log message should be FINE, it's an implementation detail that the user doesn't care about.

Change an INFO log message to FINE

---

src/org/daisy/dotify/formatter/impl/page/PageImpl.java
src/org/daisy/dotify/formatter/impl/page/PaginatorTools.java

@kalaspuffar This adds a warning message when text in the header/footer does not fit within the provided space and the "allowsTextOverflowTrimming" setting is true (otherwise an exception would be raised).
The behavior is now similar to when text in the left/right page margin does not fit (see https://github.com/mtmse/dotify.library/pull/35).
Related to https://github.com/mtmse/dotify.library/issues/23

Show warning when text in header/footer does not fit within the provided space

---

integrationtest/org/daisy/dotify/formatter/test/FlowInHeaderOrFooterTest.java
integrationtest/org/daisy/dotify/formatter/test/HyphenateTest.java
integrationtest/org/daisy/dotify/formatter/test/LayoutEngineTest.java
src/org/daisy/dotify/api/formatter/FormatterConfiguration.java
src/org/daisy/dotify/formatter/impl/sheet/SheetDataSource.java

@kalaspuffar @PaulRambags I've added a new method `allowsEndingPageOnHyphen()` to the FormatterConfiguration API along the lines of the existing `allowsEndingVolumeOnHyphen()` method, but I could also have merged the two into a single new method that accepts an enum (true|false|except-at-volume-breaks).
@fredrikschill rightly remarked that never allowing hyphenation at page breaks could also become the default behavior, and nobody would have any problems with this. This means dropping `allowsEndingVolumeOnHyphen()`.
This morning we also mentioned that we might want to make an exception for compound words: we could allow compound words to be hyphenated across pages (except at volume boundaries maybe, but we also said that we should consider to try not breaking blocks across volumes by …

Suppress hyphenation on the last line of pages

---

build.gradle

Hi @bertfrees 
Saw that Nexus reported we had a serious security issue with the Woodstox version we where running so I bumped the version to the latest one. Didn't know if it could impact anything so I've already ran the regression tests.
If this isn't impacting Pipeline I guess this could be merged without to much review.

New version of woodstox-core

---

src/org/daisy/dotify/formatter/impl/obfl/ObflParserImpl.java
src/org/daisy/dotify/formatter/impl/segment/Evaluate.java

@kalaspuffar A xml:lang attribute with an empty value is [allowed in OBFL](https://mtmse.github.io/obfl/obfl-specification.html#L2500) but when used it resulted in a `NullPointerException` in Dotify. This PR fixes that.

Support xml:lang attribute with empty value

---

src/org/daisy/dotify/formatter/impl/page/PaginatorTools.java
test/org/daisy/dotify/formatter/impl/page/PaginatorToolsTest.java

Hi @kalaspuffar @PaulRambags, I found a bug in PaginatorTools.distributeEqualSpacing(). I don't really understand why this hasn't happened before, but when a field was truncated it resulted in an AssertionError due to the `assert length == width;` line further down. This PR fixes the bug and adds a unit test.

Fix bug in PaginatorTools.distributeEqualSpacing()

---

src/org/daisy/dotify/formatter/impl/page/FieldResolver.java
test/org/daisy/dotify/formatter/impl/page/FieldResolverTest.java

Hi @PaulRambags @kalaspuffar. I fixed a bug in FieldResolver. Fields containing soft hyphens apparently resulted in a mismatch between the text and attribute lengths. I have added a unit test to demonstrate the issue.

Fix bug in FieldResolver

---

src/org/daisy/dotify/hyphenator/impl/hyphenation-catalog.xml

Hi @PaulRambags and @bertfrees 
This PR comment out the crashing Russian Latex rules (They crash on load, so they are useless).
I've prepared a UTF-8 version of the file and converted it with the [substrings.pl](https://github.com/hunspell/hyphen/blob/master/substrings.pl) script. This dictionary I've put locally in `/usr/share/hyphen`.
With these small changes, the Russian hyphenation will be handled by the Hunspell C library and use a local dictionary.
As it's loaded by C, we can't have the files bundled in the jar file. I currently don't have the time to write a java implementation for this format and MTM is waiting for a resolution to this problem. But it would be a fun challenge, and the explanation in Donald Knuth's book seems pretty straightforward, so that it might be a good …

Remove the russian tables from the LatexHyphenator configuration.

---

integrationtest/org/daisy/dotify/formatter/test/HyphenateTest.java
integrationtest/org/daisy/dotify/formatter/test/resource-files/hyphenate/hyphenate-last-line-widows-expected.pef
integrationtest/org/daisy/dotify/formatter/test/resource-files/hyphenate/hyphenate-last-line-widows-input.obfl
src/org/daisy/dotify/formatter/impl/search/CrossReferenceHandler.java

@kalaspuffar @PaulRambags It has been a while since we found one, but there are still bugs in Dotify.
The "row count" data stored in CrossReferenceHandler is used by the page break algorithm in the next iteration to determine/estimate how many widow lines a block will have. The actual row count can differ however, for instance due to changes in hyphenation (hyphenation may be suppressed on the last line of the page). This could lead to an endless alternation between two renderings. This is why I've changed it to store the *minimum* value of all iterations. Note that it could result in page breaks that happen one row too early because the row count was underestimated.

Fix another bug that resulted the dreaded "Failed to complete volume division" error

---

integrationtest/META-INF/services/org.daisy.dotify.api.translator.BrailleTranslatorFactoryService
integrationtest/MockBypassTranslatorFactoryService.java
integrationtest/org/daisy/dotify/formatter/test/LeaderTest.java
integrationtest/org/daisy/dotify/formatter/test/resource-files/leader-keep-together-expected.pef
integrationtest/org/daisy/dotify/formatter/test/resource-files/leader-keep-together-input.obfl
src/org/daisy/dotify/formatter/impl/row/SegmentProcessor.java
src/org/daisy/dotify/formatter/impl/segment/Segment.java

This is needed for the line breaker to keep a segment together on the same row as the following leader if desired.
Fixes https://github.com/mtmse/dotify.library/issues/24.
@PaulRambags @kalaspuffar

Take into account following leader when line breaking text
